config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'home/index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'tags/:tag', to: 'home#index', as: :tag
  get 'invitation_signup/:invitation_token', to: 'account_activations#new', as: 'invitation_signup'

  resources :users, :sessions, :posts
  resources :account_activations, only: [:edit, :create]

  resources :users do
    resources :groups do
      resources :invitations, only: [:new, :create]
    end
  end

  root to: 'welcome#index'

end

app/models/group.rb
class Group < ApplicationRecord #removed the require 'twitter' line - should work anyway but just making note
  attr_accessor :tweets, :twitter
  before_create :initialize_tweets
  has_and_belongs_to_many :users

  def initialize_tweets
    self.twitter = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['CONSUMER_KEY']
      config.consumer_secret     = ENV['CONSUMER_SECRET']
      config.access_token        = ENV['ACCESS_TOKEN']
      config.access_token_secret = ENV['ACCESS_TOKEN_SECRET']
    end
  end


  def get_tweets
    self.tweets = []
    self.initialize_tweets.search("#{self.description}", result_type: "recent").take(3).collect do |tweet|
      self.tweets << tweet
    end
    self.tweets
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :destroy, :edit]

  def index
    @user = current_user
    @groups = @user.groups
  end

  def show
  end

  def new
    @post = Post.new
    @group = Group.new
    @user = current_user
  end

  def edit
  end

  def create
    @user = current_user
    @group = @user.groups.create(group_params)
    if @user.activated?
      redirect_to home_index_path
    else
      redirect_to root_path
    end
  end

  def destroy
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :description)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_tweet.html.erb
<article class="mini-post">
  <header>
    <h3><a href="#"><%= tweet.user.name %></a></h3>
    <time class="published" datetime="<%= tweet.created_at %>"><%= tweet.created_at %></time>
    <a href="#" class="author"><img src="<%= tweet.user.profile_image_url %>" alt="" /></a>
  </header>
  <span class="tweet_text"><%= tweet.text %></span>
  <span class="tweet_text"><%= tweet.user.location %></span>
</article>

app/views/groups/index.html.erb
<div id="group">
	<div class="wrapper">
	<!-- Header -->
		<header class="header">	<!-- used to be #header -->
			<h1>COGENT<a href="<%= home_index_path %>" class="icon fa-home fa-lg"></a></h1>

	    <nav class="links group_links">
	      <ul>
	        <li><a href="#">Profile</a></li>
	        <li><a href="#">Visualization</a></li>
	        <li><a href="#">Feed</a></li>
	        <li><a href="#">Random</a></li>
	      </ul>
	    </nav>
		</header>

		<div class="main"> <!-- used to be #main -->

			<!-- Post -->
			<% @groups.each do |group| %>
				<article class="post">
					<header id="group_header_invite"><!-- <%= group.id %> -->
							<div class="title">
								<h2><%= group.name %></h2>
							</div>
						<div class="meta">
							<time class="published" datetime="2015-11-01"><%= group.created_at %></time>
							<a href="#" class="author"><span class="name"><br><%= current_user.username %>
							</span><%= image_tag(current_user.image, class: 'logo') %></a>
							<li><%= link_to "Invite friends", new_user_group_invitation_path(current_user, group), remote: true %></li>
						</div>
					</header>
					<footer>
						<% if group.users.any? %>
							<ul class="stats">
								<li><a href="#">MEMBERS:</a></li>
								<% group.users.each do |user| %>
									<% if user.username == current_user.username %>
										<li><a href="#" class="icon fa-user">YOU</a></li>
									<% else %>
										<li><a href="#" class="icon fa-user"><%= user.username %></a></li>
									<% end %>
								<% end %>
						<% end %>
						</ul>
					</footer>
				</article>
			<% end %>
		</div>

	<!-- Footer -->


	</div>
</div><!-- end of new_group -->

app/views/groups/new.html.erb
<div id="new_group">

	<div class="wrapper">
	<!-- Header -->
		<header class="header">	<!-- used to be #header -->
			<h1>COGENT</h1>
	    <nav class="links">
	      <ul>
	        <li><a href="#">Profile</a></li>
	        <li><a href="#">Groups</a></li>
	        <li><a href="#">Visualization</a></li>
	        <li><a href="#">Feed</a></li>
	        <li><a href="#">Random</a></li>
	      </ul>
	    </nav>
			<nav class="main">
				<ul>
					<li class="search">
						<a class="fa-search" href="#search">Search</a>
						<form id="search" method="get" action="#">
							<input type="text" name="query" placeholder="Search" />
						</form>
					</li>
					<li class="menu">
						<a class="fa-bars" href="#menu">Menu</a>
					</li>
				</ul>
			</nav>
		</header>

	<!-- Menu -->
		<!-- <%= render 'home/nav' %> -->

	<!-- Main -->
		<div class="main"> <!-- used to be #main -->

			<!-- Post -->
				<article class="post">
					<header>
						<div class="title">
							<h2><a href="#">Choose a group name</a></h2>
							<p>Invite your friends to join with Facebook or Google</p>
						</div>
						<div class="meta">
							<time class="published" datetime="2015-11-01"><%= Date.current() %></time>
							<a href="#" class="author"><span class="name">Welcome<br><%= current_user.username %>
							</span><%= image_tag(current_user.image, class: 'logo') %></a>
						</div>
					</header>
	        <div class="new_group_form_container">
	          <%= simple_form_for [@user, @group], remote: true do |f| %>
	            <%= f.input :name, input_html: { class: 'input-field' } %>
							<%= f.input :description, hint: "Separated by commas", input_html: { class: 'input-field' } %>
	            <%= f.button :submit %>
	          <% end %>
	        </div>
					<footer>
						<ul class="stats">
							<li><a href="#">General</a></li>
							<li><a href="#" class="icon fa-heart">28</a></li>
							<li><a href="#" class="icon fa-comment">128</a></li>
						</ul>
					</footer>
				</article>
		</div>

	<!-- Footer -->

		<section class="footer"><!-- used to be #footer -->
			<ul class="icons">
				<li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
				<li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
				<li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
			</ul>
			<p class="copyright">&copy; Untitled.</p>
		</section>

	</div>
</div><!-- end of new_group -->