config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'home/index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'tags/:tag', to: 'home#index', as: :tag
  get 'invitation_signup/:invitation_token', to: 'account_activations#new', as: 'invitation_signup'

  resources :users, :sessions, :posts
  resources :account_activations, only: [:edit, :create]

  resources :users do
    resources :groups do
      resources :invitations, only: [:new, :create]
    end
  end

  root to: 'welcome#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user

  def index
    @post = Post.new
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.order(created_at: :desc)
    end
    # current_user.rock_tweets.sample do |object| --> The code that almost brought the plane down. **This works in the command line**
    #   puts object.text if object.is_a?(Twitter::Tweet)
    # end
    # current_user.twitter

  end

  private
  def set_user
    if current_user
      @user = current_user
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav.html.erb
<!-- Menu -->
  <section id="menu">
    <!-- Links -->
      <header>
        <h2>COGENT GROUPS</h2>
      </header>
      <section>
        <% if current_user %>
          <% if current_user.groups.any? %>
            <ul class="links">
              <% current_user.groups.each do |group| %>
                <li>
                  <a href="#">
                    <h3><%= group.name %></h3>
                  </a>
        						<% if group.users.any? %>
                      <footer>
          							<ul class="stats">
          								<h3>MEMBERS:</h3>
          								<% group.users.each do |user| %>
          									<% if user.username == current_user.username %>
          										<li><a href="#" class="icon fa-user">YOU</a></li>
          									<% else %>
          										<li><a href="#" class="icon fa-user"><%= user.username %></a></li>
          									<% end %><!--end of if -->
          								<% end %><!--end of each -->
                        </ul>
                      </footer>
        						<% end %>
                </li>
              <% end %>
            </ul>
          <% end %>
        <% end %>
      </section>

    <!-- Actions -->
      <section>
        <h3>Add a new post</h3>
        <div class="new_post_form_container container">
          <%= simple_form_for @post, remote: true do |f| %>
            <%= f.input :title, input_html: { class: 'input-field' } %>
            <%= f.input :content, input_html: { class: 'input-field' } %>
            <%= f.input :url, input_html: { class: 'input-field' } %>
            <%= f.button :submit %>
          <% end %>
        </div>
         <ul class="actions vertical">
           <% if current_user %>
             <li><%= link_to "Log Out", signout_path, id: "sign_out", class: "button big fit" %></li>
           <% end %>
         </ul>
      </section>
  </section>

app/views/home/index.html.erb
<!-- Wrapper -->
  <div id="wrapper">

    <!-- Header -->
      <header id="header">
        <h1><a href="#">COGENT</a></h1>
        <nav class="links">
          <ul>
            <li><a href="#">Profile</a></li>
            <% if current_user %>
              <li><%= link_to "Groups", user_groups_path(current_user) %></li>
            <% end %>
            <li><a href="#">Visualization</a></li>
            <li><a href="#">Feed</a></li>
            <li><a href="#">Random</a></li>
          </ul>
        </nav>
        <nav class="main">
          <ul>
            <li class="search">
              <a class="fa-search" href="#search">Search</a>
              <form id="search" method="get" action="#">
                <input type="text" name="query" placeholder="Search" />
              </form>
            </li>
            <li class="menu">
              <a class="fa-bars" href="#menu">Menu</a>
            </li>
          </ul>
        </nav>
      </header>

    <!-- Menu -->
        <%= render 'nav' %>
    <!-- Menu End -- >

    <!-- Main -->
      <div id="main">

        <!-- Appending post partial here -->
        <%= render @posts %>
      </div>

    <!-- Sidebar -->
      <section id="sidebar">

        <!-- Intro -->
          <section id="intro">
            <%= image_tag(current_user.image, class: 'logo') %>
            <header>
              <h2>COGENT Dashboard</h2>
              <p>The curated news feed</p>
              <p>Inherently relevant</p>
            </header>
          </section>

        <!-- Mini Posts -->
          <section>
            <div class="mini-posts">
              <% current_user.groups.each do |group| %>
                <% group.get_tweets.each do |tweet| %>
                  <%= render partial: 'groups/tweet', locals: { tweet: tweet} %>
                <% end %>
              <% end %>
            </div>
          </section>

        <!-- Posts List -->
          <section>
            <ul class="posts">
              <li>
                <article>
                  <header>
                    <h3><a href="#">Lorem ipsum fermentum ut nisl vitae</a></h3>
                    <time class="published" datetime="2015-10-20">October 20, 2015</time>
                  </header>
                  <a href="#" class="image"><img src="images/pic08.jpg" alt="" /></a>
                </article>
              </li>
              <li>
                <article>
                  <header>
                    <h3><a href="#">Convallis maximus nisl mattis nunc id lorem</a></h3>
                    <time class="published" datetime="2015-10-15">October 15, 2015</time>
                  </header>
                  <a href="#" class="image"><img src="images/pic09.jpg" alt="" /></a>
                </article>
              </li>
              <li>
                <article>
                  <header>
                    <h3><a href="#">Euismod amet placerat vivamus porttitor</a></h3>
                    <time class="published" datetime="2015-10-10">October 10, 2015</time>
                  </header>
                  <a href="#" class="image"><img src="images/pic10.jpg" alt="" /></a>
                </article>
              </li>
              <li>
                <article>
                  <header>
                    <h3><a href="#">Magna enim accumsan tortor cursus ultricies</a></h3>
                    <time class="published" datetime="2015-10-08">October 8, 2015</time>
                  </header>
                  <a href="#" class="image"><img src="images/pic11.jpg" alt="" /></a>
                </article>
              </li>
              <li>
                <article>
                  <header>
                    <h3><a href="#">Congue ullam corper lorem ipsum dolor</a></h3>
                    <time class="published" datetime="2015-10-06">October 7, 2015</time>
                  </header>
                  <a href="#" class="image"><img src="images/pic12.jpg" alt="" /></a>
                </article>
              </li>
            </ul>
          </section>

        <!-- About -->
          <section class="blurb">
            <h2>About</h2>
            <p>This is a capstone project by Liam Ellis. It was hard and a lot went it to it. So far so good. Code on brethren</p>
          </section>

        <!-- Footer -->
          <section id="footer">
            <ul class="icons">
              <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
              <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
              <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
              <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
              <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
            </ul>
            <p class="copyright">&copy; Aestheke Inc.</p>
          </section>

      </section>

  </div>

<!-- Scripts -->
  <script src="assets/js/jquery.min.js"></script>
  <script src="assets/js/skel.min.js"></script>
  <script src="assets/js/util.js"></script>
  <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
  <script src="assets/js/main.js"></script>

</body>
</html>