config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'home/index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'tags/:tag', to: 'home#index', as: :tag
  get 'invitation_signup/:invitation_token', to: 'account_activations#new', as: 'invitation_signup'

  resources :users, :sessions, :posts
  resources :account_activations, only: [:edit, :create]

  resources :users do
    resources :groups do
      resources :invitations, only: [:new, :create]
    end
  end

  root to: 'welcome#index'

end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :thumbnailer

  belongs_to :user
  acts_as_taggable_on :tags
  validates :content, :title, presence: true

  def get_user
    user = User.find(self.user_id)
  end

  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :destroy, :update]

  def new
  end

  def index
  end

  def show
  end

  def edit
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def create
    @post = current_user.posts.create(post_params)
    @post.thumbnailer = LinkThumbnailer.generate(post_params[:url])

    binding.pry
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def update
    if !(@post.tag_list.include?(params[:value]))
      @post.tag_list.add(params[:value])
      @post.save
      @tag = params[:value]
      respond_to do |format|
        format.html { redirect_to 'home#index' }
        format.js
      end
    else
      flash[:notice] = "Well, that didn't quite work did it?"
      redirect_to home_index_path
    end
  end

  def destroy

  end

  private

  def post_params
    params.require(:post).permit(:content, :title, :url, :user_id, :tag_list, :value)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_add_tag.html.erb
<!-- <div id="add_tag_buttons" class=""> -->
  <li class="tag_button">
    <%= button_to "Dope", post_path(post), { params: { value: 'dope'}, method: 'patch', remote: true, class: ""} %>
  </li>
  <li class="tag_button">
    <%= button_to "Meh", post_path(post), { params: { value: 'meh'}, method: 'patch', remote: true, class: ""} %>
  </li>
  <li class="tag_button">
    <%= button_to "Yikes", post_path(post), { params: { value: 'yikes'}, method: 'patch', remote: true, class: ""} %>
  </li>
<!-- </div> -->

app/views/posts/_post.html.erb
<article class="post">
  <header>
    <div class="title">
      <h2><a href="#"><%= post.title %></a></h2>
      <% if post.thumbnailer != nil %>
        <p><%= post.thumbnailer.description %></p>
      <% end %>
      <ul id="tags_<%= post.id %>" class="">
        <% if post.tag_list.any? %>
          <% post.tag_list.each do |tag| %>
            <%= render partial: 'posts/tag', locals: { tag: tag } %>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div class="meta">
      <time class="published" datetime=""><%= post.created_at %></time>
      <a href="#" class="author"><span class="name"><%= post.get_user.username %></span><%= image_tag(post.get_user.image) %></a>
    </div>
  </header>
  <% if post.thumbnailer != nil %>
    <a href="<%= post.url %>" class="image featured"><img src="<%= post.thumbnailer.images.first.src %>" alt="" /></a>
  <% end %>

  <p id="<%= post.id %>_content"><%= post.content %></p>
  <footer>
    <!-- <ul class="actions">
      <li><a href="#" class="button big">Continue Reading</a></li>
    </ul> -->
    <ul class="stats" id="<%= post.id %>">
      <li><a href="#" class="icon fa-heart">28</a></li>
      <li><a href="#" class="icon fa-comment">128</a></li>
      <% if post.thumbnailer != nil %>
        <li><%= post.thumbnailer.title %></li>
      <% end %>
      <li><%= link_to "Tag this", edit_post_path(post), class: "tag_link", remote: true %></li>
    </ul>
  </footer>
</article>

app/views/posts/_tag.html.erb
<li class="tag"><%= link_to tag, tag_path(tag) %></li>

app/views/posts/create.js.erb
$('#main').prepend("<%= j render partial: 'post', locals: { post: @post } %>");

app/views/posts/edit.js.erb
$('#<%= @post.id %>').find('.tag_link').fadeOut(500);
$('#<%= @post.id %>').append("<%= j render partial: 'posts/add_tag', locals: { post: @post } %>");

app/views/posts/update.js.erb
$('#add_tag_buttons').hide();
$('#tags_<%= @post.id %>').append("<%= j render partial: 'posts/tag', locals: { tag: @tag } %>");